# Generated by Django 2.2.3 on 2019-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('google_map', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('go', models.TextField()),
                ('video', models.CharField(max_length=200)),
            ],
        ),
    ]
