# Generated by Django 2.2.3 on 2019-08-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fortune_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fortune.Fortune')),
            ],
        ),
        migrations.AddField(
            model_name='fortune',
            name='entries',
            field=models.ManyToManyField(blank=True, to='fortune.User'),
        ),
    ]
