# Generated by Django 2.2.3 on 2019-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='fortune',
            old_name='finish',
            new_name='finishtime',
        ),
        migrations.RemoveField(
            model_name='fortune',
            name='time',
        ),
    ]
