# Generated by Django 2.2.3 on 2019-08-08 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_auto_20190809_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='datetime',
            new_name='calcuate',
        ),
        migrations.AddField(
            model_name='fortune',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortune',
            name='starttime',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fortune',
            name='finishtime',
            field=models.CharField(max_length=500),
        ),
    ]
