# Generated by Django 2.2.3 on 2019-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_auto_20190809_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fortune_id',
            field=models.IntegerField(),
        ),
    ]
