# Generated by Django 2.2.3 on 2019-08-09 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0008_auto_20190809_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortune',
            name='seat',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
